spring:
  profiles:
    active: server  # 현재 로컬로 돌리기 위해 local로 설정

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    multipart:    # 파일 크기 지정
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      force-response: true
